---
title: "lastfm"
output: html_document
date: "2023-07-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# devtools::install_github("ppatrzyk/lastfmR")
require(lastfmR)
require(googlesheets4)
require(stringi)
require(RCurl)
require(Hmisc)
require(rms)
require(ggplot2)
require(lubridate)
require(magrittr)
require(dplyr)
require(knitr)
require(kableExtra)
require(tidyr)
require(stringr)
require(forcats)
require(plotly)
require(gtsummary)
require(gt)
require(reactable)
require(reactablefmtr)
require(htmltools)
require(readxl)
require(ggbeeswarm)
library(scrobbler)

options(
  gargle_oauth_cache = ".secrets",
  gargle_oauth_email = TRUE
)

# now use googledrive with no need for explicit auth
gs4_auth(
  cache = ".secrets",
  email = "jjdeclercq@gmail.com"
)

clean.tracks <- function(dat){
  dat %>% separate(track, into = c("track", "junk"), sep = " - ")%>% 
  separate(., track, into = c("track", "extra2"), sep = " \\[", fill = "right") %>% 
  separate(., track, into = c("track", "extra"), sep = " \\(", fill = "right")
  
}

fix_albums <- read_sheet("1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "fix_albums")
fix_artists <- read_sheet("1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "fix_artists")

```

```{r}

# scrobbles <- lastfmR::get_scrobbles(user = "jjdeclercq")

# my_data <- download_scrobbles(username = "jjdeclercq", api_key = "af685b724bb505055968e9f178a6b989")
Load(jj_scrobb)
jj_scrobb <- update_scrobbles(jj_scrobb, 
                                    timestamp_column = 'date_unix',
                                    username = "jjdeclercq",
                                    api_key = "af685b724bb505055968e9f178a6b989")
Save(jj_scrobb)

scr_long <- jj_scrobb %>% mutate(date = ymd(strptime(gsub(",.*", "", date), format = "%d %b %Y"))) %>% 
  group_by(artist, album) %>% 
  separate(., album, into = c("album", "extra2"), sep = " \\[", fill = "right") %>% 
  separate(., album, into = c("album", "extra"), sep = " \\(", fill = "right") %>% 
  left_join(., fix_artists,  by = c("artist")) %>% mutate(artist = ifelse(!is.na(fix.a), fix.a, artist)) %>% 
    mutate(a1 = tolower(artist), a1 = stri_trans_general(a1, 'latin-ascii')) %>% 
    left_join(., fix_albums,  by = c("a1", "album")) %>% mutate(album = ifelse(!is.na(fix), fix, album)) %>% 
  mutate(a2 = tolower(album), a2 = stri_trans_general(a2, 'latin-ascii')) %>% select(-extra, -extra2, -fix.a, -fix) %>% 
  rename(track = song_title)

scr_tal <- scr_long %>%  group_by(a1, a2) %>% clean.tracks() %>% 
 summarise(artist = first(artist), album = first(album), 
           n = n(), 
           n_ytd = sum(date >= ymd("2024.01.01"), na.rm = TRUE), 
           n_365 = sum(date >= (today()-days(365)), na.rm = TRUE), 
           n_30 = sum(date >= (today()-days(30)), na.rm = TRUE),
           last_played = max(date, na.rm = TRUE), tracks = n_distinct(track), 
           .groups = "drop")



sheet <- read_sheet("1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "All")%>% mutate(artist = trimws(artist)) %>% 
  mutate(a1 = tolower(artist), a1 = stri_trans_general(a1, 'latin-ascii')) %>% 
  mutate(a2 = tolower(album), a2 = stri_trans_general(a2, 'latin-ascii')) %>% select(-n, -starts_with("n_"))


added_n <- left_join(sheet %>% select(-last_played, -tracks), scr_tal %>% select(-artist, -album), by = c("a1", "a2")) %>% 
  select(-a1, -a2) %>% 
  mutate(n = replace_na(n, 0)) %>% mutate(play_ratio = round(n/tracks, 1)) %>% 
  select(Order, artist, album, Year, Status, n, play_ratio, tracks,
                                          last_played,a_rank,p_rank, ranker,matches,starts_with("n_"), Rank, Tier, within_year) %>% 
  arrange(a_rank, Status, desc(play_ratio), Year)

# Will add number of scrobbles
write_sheet(added_n, "1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "All")

# jj_scrobb %>% mutate(date = ymd(strptime(gsub(",.*", "", date), format = "%d %b %Y"))) %>% 
#   group_by(artist, album) %>% 
#   separate(., album, into = c("album", "extra2"), sep = " \\[", fill = "right") %>% 
#   separate(., album, into = c("album", "extra"), sep = " \\(", fill = "right") %>% 
#   left_join(., fix_artists,  by = c("artist")) %>% ungroup() %>% slice(14548)

# added_n %>% filter(Status == "Keep", is.na(a_rank)) %>% j.reactable()
# 
# added_n %>% mutate(Status = case_when(!is.na(a_rank) ~ "Ranked", 
#                                  Status == "Keep"& is.na(a_rank) ~ "Add",
#                                  Status == "Borrowed"& is.na(a_rank) ~ "Drop",
#                                  Status == "Compilation"& is.na(a_rank) ~ "Songs",
#                                  Status == "Sample"& is.na(a_rank) ~ "Homework",
#                                  TRUE ~ Status)) %>% arrange(a_rank, Status, desc(play_ratio), Year) %>% 
#   write_sheet(., "1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "All")
```




# Scrobbles
```{r}
scr_long %>% select(1:5) %>% head(50) %>% j.reactable()



scr_long %>% clean.tracks() %>% 
  group_by(a1, a2, track) %>% summarise(n = n()) %>% arrange(desc(n)) %>% j.reactable()
```

```{r}
## Scrobbles not accounted for in sheet
## 73% 10/23
## 74.19% 10/26, then 74.48%
## 74.94 10/31, then 76.25
## 77.59 11/1
## 77.97 11/2
## 78.17 11/7
## 78.70 11/21
## 78.8  12/21
## 78.9  1/31/24
## 79.2 4/17/24
## 81.2 4/30/24


scr_tal %>% left_join(., sheet %>% select(a1, a2) %>% mutate(b = "x"), by = c("a1", "a2")) %>% 
  mutate(b = replace_na(b, "y")) %>% 
  group_by(b) %>% summarise(n = sum(n)) %>% 
  mutate(pct = n/sum(n)) %>% jgtt()

# added_n %>% filter(artist == "Judas Priest") %>% select(1:4) %>% write.csv("jp_albums.csv")

# jpa <- read.csv("../ranker/jp_albums.csv")
# added_n %>% filter(Tier %in% 1:3) %>% sample_n(200) %>% select(1:4) %>% bind_rows(., jpa) %>% distinct() %>% write.csv("../ranker/jp_albums.csv", rownames = FALSE)
# added_n %>% count(artist, album, sort = TRUE)

j.reactable(added_n, filterable = TRUE)
added_n %>% filter(is.na(a_rank)) %>% j.reactable(., filterable = TRUE)

added_n[grepl(paste(as.character(NULL),collapse="|"), added_n$artist),]
```

```{r}
#| eval: false


library(urltools)
build_artist_toptags_query <- function(artist, api_key = "af685b724bb505055968e9f178a6b989", base = "http://ws.audioscrobbler.com/2.0/") {
  base <- param_set(base, "method", "artist.gettoptags")
  base <- param_set(base, "artist", URLencode(artist))
  base <- param_set(base, "api_key", api_key)
  base <- param_set(base, "format", "json")

  return(base)
}

fetch_artist_toptags <- function(artist) {
  # print(paste0("Fetching ", artist))
  json <- jsonlite::fromJSON(build_artist_toptags_query(artist))
  if (length(json$toptags$tag) == 0) return(data.frame(artist = artist, tag = NA))
  x <- data.frame(artist = artist, tag = json$toptags$tag[,"name"]) %>% 
    mutate(tag = tolower(tag), tag = gsub("-", " ", tag)) %>% distinct()
  
  return(x)
}

Load(art_tags)

  add_arts <- added_n %>% filter(n > 0, artist %nin% art_tags$artist) %>% pull(artist) %>% unique()
  add_art_tags <- map(add_arts, fetch_artist_toptags) %>% list_rbind()
  art_tags <- bind_rows(art_tags, add_art_tags) %>% distinct()
  
Save(art_tags)


# art_tags %>% group_by(tag) %>% mutate(n = n()) %>% filter(n >5)

# art_tags %>% count(tag, sort = TRUE)%>% filter(n >=9) %>% write.csv("genres.csv", row.names = FALSE)

art_tags %>% group_by(artist) %>% slice(1)%>% ungroup() %>% count(tag, sort = TRUE)

art_tags %>% group_by(artist) %>% slice(1) %>% ungroup( ) %>% select(tag) %>% jgt(., order.cat = TRUE)

art_tags %>% filter(tag %in% "horror punk")
fetch_artist_toptags("Joan Jett" )

genres <- read.csv("genres.csv") %>% filter(use ==1)

vcg <- art_tags %>% filter(tag %in% genres$tag) %>% mutate(x = 1) %>% pivot_wider(., names_from = "tag", values_from = x, values_fill = 0) %>% 
  select(-artist) %>% as.matrix() %>% varclus()

# plot(vcg)

art_tags %>% filter(tag %in% c("country", "metal"))

AT <- art_tags %>% filter(tag %in% genres$tag) %>% group_by(artist) %>% slice(1:4) %>% filter(tag %in% genres$tag)%>% mutate(x = 1) %>% 
  pivot_wider(., names_from = "tag", values_from = x, values_fill = 0) %>% ungroup()


AT %>% 
  filter(`alt country` == 1, `thrash` ==0) %>% 
  select(artist) %>% left_join(., added_n, by = "artist") %>% arrange(a_rank, desc(play_ratio)) %>% 
  j.reactable()


AT %>% rowwise() %>%
  mutate(G = sum(across(where(is.numeric)))) %>% select(1, G) %>% arrange(G)

added_n %>% group_by(Year)%>% 
   arrange(a_rank) %>% 
  summarise(albums = n(), plays = sum(n, na.rm = TRUE), 
            tracks = sum(tracks, na.rm = TRUE), 
            last_played = max(last_played, na.rm = TRUE),
            ranked_albums = sum(!is.na(a_rank)), 
            top100 = sum(a_rank <= 100, na.rm = TRUE), 
            top250 = sum(a_rank <= 250, na.rm = TRUE),
            mean3 = ifelse(ranked_albums >=3, floor(mean(head(a_rank, 3))), NA),
            keep = sum(Status == "Keep"),
            blue = sum(Status == "Blue"),
            homework = sum(Status == "Homework")) %>% j.reactable()

AT %>% 
   left_join(added_n, ., by = "artist") %>% arrange(a_rank, desc(play_ratio)) %>% select(indie:last_col()) %>% 
  summarise_all(~sum(.x, na.rm = TRUE)) %>% mutate(g = 1) %>% pivot_longer(., -g) %>% select(-g) %>% arrange(desc(value))
```

## Albums
```{r}
scr_tal %>% left_join(., sheet %>% select(a1, a2) %>% mutate(b = "x"), by = c("a1", "a2")) %>% 
  mutate(b = replace_na(b, "y")) %>% #rename(album = a2, artist = a1) %>% 
  group_by(album, artist, b, last_played) %>% summarise(n = sum(n)) %>% 
  pivot_wider(., names_from = "b", values_from = "n", values_fill = 0) %>% 
  mutate(plays = x + y) %>% 
  j.reactable()


# scr_tal %>% left_join(., sheet %>% select(a1, a2) %>% mutate(b = "x"), by = c("a1", "a2")) %>% 
#   mutate(b = replace_na(b, "y")) %>% #rename(album = a2, artist = a1) %>% 
#   group_by(album, artist, b, last_played) %>% summarise(n = sum(n)) %>% 
#   pivot_wider(., names_from = "b", values_from = "n", values_fill = 0) %>% 
#   mutate(plays = x + y) %>% filter(y > 30) %>% select(artist, album) %>% clipr::write_clip()

# scr_tal %>% filter(album == "Encanto")%>% select(artist, album) %>% clipr::write_clip()
```

## Artists
```{r}
scr_tal %>% left_join(., sheet %>% select(a1, a2) %>% mutate(b = "x"), by = c("a1", "a2")) %>% 
  mutate(b = replace_na(b, "y")) %>% 
  group_by(album, artist, b) %>% summarise(n = sum(n), last_played = max(last_played), tracks = max(tracks)) %>% 
   group_by(artist, b) %>% summarise(n = sum(n), last_played = max(last_played), tracks = sum(tracks) ) %>% 
   group_by(artist) %>% mutate(last_played = max(last_played), tracks = sum(tracks)) %>% 
  pivot_wider(., names_from = "b", values_from = "n", values_fill = 0) %>% 
  mutate(plays = x + y, ppt = round(plays/tracks, 1)) %>% 
  j.reactable()

```


# 2024 listening
```{r}
scr_long %>%  group_by(a1, a2) %>% clean.tracks() %>% #filter(date >= ymd("2024.01.01")) %>% 
 summarise(artist = first(artist), album = first(album), 
           n_ytd = sum(date >= ymd("2024.01.01")), 
           n_365 = sum(date >= (today()-days(365))), 
           n_30 = sum(date >= (today()-days(30))), 
           .groups = "drop") %>% j.reactable()
```

```{r}
# ## Finding artists that are not in both
# fa <-fuzzyjoin::stringdist_join(sheet %>% select(a1)%>%distinct(), scr_tal %>% select(a1) %>%distinct(),
#                 by='a1', #match based on team
#                 mode='left', #use left join
#                 method = "jw", #use jw distance metric
#                 max_dist=99, 
#                 distance_col='dist')
# 
# fa %>%group_by(a1.x) %>% mutate(min_dist = min(dist)) %>% filter(dist <= min_dist ) %>%filter(min_dist >0) %>%arrange(min_dist)


# inner_join(sheet, scr_tal, by = c("a1", "a2")) %>% j.reactable()
# 
# anti_join(sheet, scr_tal, by = c("a1", "a2")) %>% j.reactable()

# ## Artists that match both data sets
# artist_match <- inner_join(sheet %>% select(-album), scr_tal%>% select(-album), by = c("artist")) %>% 
#   select(artist, n) %>% distinct() %>% group_by(artist) %>% 
#   summarise(n = sum(n)) %>% distinct()
# 
# ## All artists
# artist_all <- sheet %>% group_by(artist) %>% summarise()
# 
# 
# anti_join(artist_all, artist_match, by = "artist")
```


```{r}
ggplotly(added_n %>% filter(!is.na(a_rank)) %>% mutate(t = as.numeric(today()-last_played)/365) %>% 
  ggplot(., aes(x = a_rank, y = t, label = album)) +geom_point())
```


```{r}
f2 <-fuzzyjoin::stringdist_join(
  anti_join(sheet, scr_tal, by = c("a1", "a2")), 
  scr_tal %>% select(artist, a2, album) %>%distinct(),
                by=c('a1', "a2"), #match based on team
                mode='left', #use left join
                method = "jw", #use jw distance metric
                max_dist=99, 
                distance_col='dist')

## Continue work here to batch update multiple albums
updated.albums <- f2 %>% filter(a1.dist < .1, a2.dist < 0.25) %>% select(artist = artist.x, album = album.x, album.y, a2.dist) %>% 
  group_by(album) %>% filter(a2.dist == min(a2.dist)) %>% 
  left_join(sheet, ., by = c("artist", "album")) %>% 
  mutate(album = ifelse(!is.na(album.y.y), album.y.y, album)) %>% 
  select(1:9)

# write_sheet(updated.albums, "1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "All")
```


```{r}
added_n %>% #filter(Rank %nin% c("", NA)) %>% 
j.reactable(., filterable = TRUE)


# added_n %>% filter(n ==0)
j.reactable(sheet)
```

## Status by artist
```{r}
added_n %>% 
  mutate(unranked = yesno(Rank %in% c(NA, "")))  %>% group_by(artist, Status) %>% tally() %>%
  pivot_wider(., names_from = "Status", values_from = "n", values_fill = 0) %>% 
  mutate(albums = sum(across(where(is.numeric)))) %>% 
  j.reactable()

ggplotly(added_n %>% group_by(Year, Status) %>% tally() %>%
  ggplot(., aes(x = Year, y = n, fill = Status)) +geom_bar(stat = "identity"))

added_n %>% group_by(Year) %>% summarise(plays = sum(n)) %>% ggplot(., aes(x = Year, y = plays)) +geom_bar(stat=  "identity")
```

## Plays by year
```{r}
ggplotly(added_n %>% group_by(Year) %>% summarise(n = sum(n)) %>%
  ggplot(., aes(x = Year, y = n)) +geom_bar(stat = "identity"))
```

## Albums by year
```{r}
ggplotly(added_n %>% group_by(Year) %>% summarise(n = n()) %>%
  ggplot(., aes(x = Year, y = n)) +geom_bar(stat = "identity"))

ggplotly(added_n %>% filter(n == 0) %>% group_by(Year) %>% summarise(n = n()) %>%
  ggplot(., aes(x = Year, y = n)) +geom_bar(stat = "identity"))

added_n %>% filter(n == 0) %>% j.reactable()
```

## Play ratio by year
```{r}
require(glue)
ggplotly(added_n %>% group_by(Year) %>% summarise(albums = n(), n = sum(n)) %>%
           mutate(ratio = n/albums, text = glue("albums: {albums}\n plays: {n}")) %>% 
  ggplot(., aes(x = Year, y = ratio, text = text)) +geom_bar(stat = "identity"))

added_n %>% group_by(Year) %>% summarise(albums = n(), n = sum(n)) %>%
           mutate(ratio = n/albums) %>% j.reactable()
```

## Rank by year
```{r}
added_n %>% filter(!is.na(a_rank)) %>% group_by(Year) %>% arrange(a_rank) %>% slice(1:5) %>%
  ggplot(., aes( x = Year, y = a_rank)) +geom_point() +geom_smooth()

added_n %>% filter(!is.na(a_rank)) %>% group_by(Year) %>% arrange(a_rank) %>% slice(1:5) %>% group_by(Year) %>% 
  summarise(n = n(), m = mean(a_rank)) %>% filter(n == 5) %>% arrange(m)

ggplotly(added_n %>% filter(!is.na(a_rank)) %>% group_by(Year) %>% arrange(a_rank) %>% slice(1) %>% 
  ggplot(., aes(x= Year, y = a_rank, text = album)) + geom_point())
```


```{r}
# ## remove parenthesis
# scr_tal %>% filter(artist== "Black Sabbath") %>% separate(., album, into = c("album", "extra"), sep = " \\(") %>% 
#   group_by(artist, album) %>% summarise(n = sum(n)) %>% 
#   mutate(a2 = tolower(album)) %>% 
#   arrange(artist, a2, desc(n)) %>% 
#   group_by(artist, a2) %>% summarise(n = sum(n), album = first(album))
# 
# ## deal with capitalization issues
# scr_tal %>% filter(artist== "Halsey") %>% separate(., album, into = c("album", "extra"), sep = " \\(", fill= "right") %>% 
#   group_by(artist, album) %>% summarise(n = sum(n)) %>% 
#   mutate(a2 = tolower(album)) %>% 
#   arrange(artist, a2, desc(n)) %>% 
#   group_by(artist, a2) %>% summarise(n = sum(n), album = first(album))
# 
# ## Block parens
# scr_tal %>% #filter(artist== "Clutch") %>% 
#   separate(., album, into = c("album", "extra2"), sep = " \\[", fill = "right") %>% 
#   separate(., album, into = c("album", "extra"), sep = " \\(", fill = "right") %>% 
#   group_by(artist, album) %>% summarise(n = sum(n)) %>% mutate(a2 = tolower(album)) %>% 
#   arrange(artist, a2, desc(n)) %>% 
#   group_by(artist, a2) %>% summarise(n = sum(n), album = first(album)) %>% j.reactable()
# 
# # (watch my moves)
# # Come What(ever) May
# 
# scr_tal %>% filter(a2 %in% c("hamilton", "frozen", "frozen 2"))
```

```{r}
## Song lengths can be tricky!
scrobbles %>% arrange(date) %>% mutate(song_length = round(as.numeric(date-lag(date))/60, 2) )%>% filter(!is.na(song_length)) %>%

  # filter(song_length < 60) %>% 
  group_by(artist, album, track) %>% 
    mutate(n = n()) %>% filter(n >1) %>% 
    arrange(artist, album, track) %>% filter(n >10)
  summarise( min = min(song_length), mode = DescTools::Mode(song_length),mean = mean(song_length), sd = sd(song_length)) 
  

scrobbles %>% filter(grepl("Inside Room", album))%>% arrange(date) %>% mutate(song_length = as.numeric(date-lag(date)) )%>% filter(!is.na(song_length)) %>% group_by(artist, album, track) %>% summarise(n = n(), min = min(song_length), mode = DescTools::Mode(song_length), sd = sd(song_length))
```



```{r}

# scr_lib <- get_library_info(user = "jjdeclercq", user_scrobbles_only = FALSE)
# 
# 
# scr_lib %>% mutate(ratio = round(100*user_scrobbles/global_scrobbles, 4) )%>% arrange(desc(ratio))

edgelist <- get_similar('Blind Guardian')
# level2 <- rbindlist(lapply(
#   edgelist[, To], get_similar
# ))
# edgelist <- rbindlist(list(edgelist, level2))
# 
# edgelist %>% filter(match == 1)

edgelist %>% filter(To %in% added_n$artist)
```

```{r}
songs <- read.csv("liked_20231102.csv") %>% namify() %>% 
  rename(album = album_name, artist = artist_name_s_, date = release_date) %>%
  separate(., album, into = c("album", "extra2"), sep = " \\[", fill = "right") %>% 
  separate(., album, into = c("album", "extra"), sep = " \\(", fill = "right")%>% 
  left_join(., fix_artists,  by = c("artist")) %>% mutate(artist = ifelse(!is.na(fix.a), fix.a, artist)) %>% 
    mutate(a1 = tolower(artist), a1 = stri_trans_general(a1, 'latin-ascii')) %>% 
    left_join(., fix_albums,  by = c("a1", "album")) %>% mutate(album = ifelse(!is.na(fix), fix, album)) %>% 
  mutate(a2 = tolower(album), a2 = stri_trans_general(a2, 'latin-ascii'),y2 = str_sub(date, 1,4))%>% 
  mutate(a1 = gsub(",.*","",a1))


j.reactable(songs)

song_albums <- songs  %>% group_by(artist, album) %>% summarise(n.songs =n())
song_albums %>% group_by(artist) %>% summarise(n = sum(n.songs))

scr_tal %>% select(-artist, -album) %>% 
  left_join(., 
songs %>% group_by(a1, a2) %>% summarise(liked = n()), 
by = c("a1", "a2")) %>% j.reactable()

scr_tal %>% select(-artist, -album) %>% 
  left_join( 
songs %>% group_by(a1, a2) %>% summarise(liked = n()), ., 
by = c("a1", "a2")) %>% j.reactable()

songs %>% filter(grepl(",", a1)) 
str_split()
```

## Duplicate liked songs
```{r}
songs %>% group_by(a1, a2, track_name) %>% tally() %>% filter(n > 1)
```

# Artist trajectories
```{r}
artist_traj <- function(ARTISTS){
  
  ggplotly(scr_long %>% filter(artist %in% ARTISTS) %>% 
  mutate(date = as.Date(date)) %>% arrange(date) %>% group_by(artist, date) %>% tally() %>% 
  group_by(artist) %>% mutate(N = cumsum(n)) %>% 
  ggplot(., aes(x = date, y = N, colour = artist)) +geom_step())
  
}


att <- c("Katatonia",  "Carly Rae Jepsen", "Blind Guardian",  
  "The Replacements", "Gang of Four", "Judas Priest", "Elton John", "Warren Zevon", "Van Halen",
                                   "Savatage", "The Cure", "Motörhead",
                                   "Protest the Hero"#,  "Rush", "New Model Army", "Run the Jewels"
  )

artist_traj(att)
```

```{r}
# added_n %>% filter(Year == 2023) %>% arrange(desc(n)) %>% select(2:3, n) %>% 
#   write_sheet(., "1F1bi8Y12cnmyCnNB3HWpVdj9oi918ohHi7qBITB73Ks", sheet = "2023")
```

```{r}
added_n %>% filter(Tier == 1) %>% filter(Order %in% sample(Order, 4, TRUE))
```



```{r eval = FALSE}

## Spotify API
devtools::install_github('charlie86/spotifyr')
require(spotifyr)

# https://developer.spotify.com/dashboard/76290730fe0d45d88d925789ea5306b1

Sys.setenv(SPOTIFY_CLIENT_ID = '76290730fe0d45d88d925789ea5306b1')
Sys.setenv(SPOTIFY_CLIENT_SECRET = 'copy from website above')

access_token <- get_spotify_access_token()


baroness <- get_artist_audio_features('baroness')

baroness %>% 
    count(key_mode, sort = TRUE) %>% 
    head(5)

get_album("7mv4FQrLiyJWLDazVNZzTi")
```


<!-- ```{r} -->
<!-- tha <- read_xlsx("/Users/joshdeclercq/Downloads/NPI File_3.29.24.xlsx", sheet = 1) %>% mutate(source = "tha") -->
<!-- epsi <- read_xlsx("/Users/joshdeclercq/Downloads/NPI File_3.29.24.xlsx", sheet = 2)  -->


<!-- left_join(tha, epsi, by = "Attending NPI") %>% write.csv(., "wink.csv") -->

<!-- left_join(epsi, tha %>% select(1, source), by = "Attending NPI") %>% write.csv(., "wink2.csv") -->
<!-- ``` -->

